import React, {useEffect, useMemo, useRef, useState} from 'react';
import './agent-session.css';
import {useNavigate, useParams} from 'react-router-dom';
import {Background, Controls, Handle, MiniMap, Position, ReactFlow} from '@xyflow/react';
import {Bot, Check, ChevronRight, Database, MessageSquarePlus, Network, Play, Save, Search, Send, Settings2, Trash2, X} from 'lucide-react';

const API='/api';
type Role='ANALYST'|'STAFF'|'COMMANDER'|'ADMIN';
type Session={user_id:string;role:Role;area:string;permissions:string[]};
type ReactAgent={id:string;name:string;description:string;role:Role;owner:string;lifecycle:string;version:number;definition:any};
type Tool={id:string;name:string;kind:string;description:string};
type ChatSession={id:string;title:string;turn_count:number;created_at:string;updated_at:string};
type ChatTurn={id:string;prompt:string;answer:string;status:string;created_at:string};

async function api(path:string,session:Session,options:RequestInit={}){
  const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json','X-Demo-Role':session.role,...(options.headers||{})}});
  if(!response.ok){const body=await response.json().catch(()=>({detail:response.statusText}));throw new Error(body.detail||response.statusText)}
  return response.json();
}

function Header({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){
  return <div className="pageHead"><div><span>{eyebrow}</span><h1>{title}</h1></div><div>{children}</div></div>;
}

function Life({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}>{value==='PUBLISHED'?'게시됨':'초안'}</span>}

function ResourceNode({data}:any){return <div className={'reactResource '+data.kind}><Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Left}/><span>{data.kind==='database'?<Database/>:data.kind==='search'?<Search/>:<Network/>}</span><div><small>{data.kind}</small><b>{data.label}</b></div></div>}
function CoreNode(){return <div className="reactCore"><Handle type="target" position={Position.Left}/><Handle type="source" position={Position.Right}/><Bot/><div><small>REACT RUNTIME</small><b>추론 · 도구 선택 · 관찰</b></div></div>}
function GoalNode(){return <div className="reactGoal"><Handle type="source" position={Position.Right}/><Send/><div><small>USER GOAL</small><b>사용자 요청</b></div></div>}
const nodeTypes:any={resource:ResourceNode,core:CoreNode,goal:GoalNode};

export function ReactAgentRegistry({session}:{session:Session}){
  const nav=useNavigate();const [items,setItems]=useState<ReactAgent[]>([]);const [creating,setCreating]=useState(false);const [name,setName]=useState(session.role==='ADMIN'?'인사행정 지원 에이전트':'파주시 조사 지원 에이전트');const [error,setError]=useState('');
  const load=()=>api('/react-agents?role='+session.role,session).then(setItems).catch((e)=>setError(e.message));
  useEffect(()=>{load()},[session.role]);
  async function create(){try{const result=await api('/react-agents',session,{method:'POST',body:JSON.stringify({name,description:'외부 데이터와 기능을 활용해 사용자의 조사 목표를 수행합니다.'})});nav('/react-agents/'+result.id+'/builder')}catch(e:any){setError(e.message)}}
  async function remove(item:ReactAgent){if(['react-paju-briefing','react-weekly-movement'].includes(item.id)||!confirm(`'${item.name}' 에이전트를 삭제하시겠습니까?`))return;await api('/react-agents/'+item.id,session,{method:'DELETE'});load()}
  return <><Header eyebrow="REACT AGENT REGISTRY" title="에이전트 레지스트리"><button className="primary" onClick={()=>setCreating(true)}><Bot/> 새 에이전트</button></Header>
    <section className="agentIntro"><Bot/><div><h2>목표 중심 ReAct 에이전트</h2><p>워크플로우는 정해진 순서로 실행되고, 에이전트는 연결된 도구 중 다음 행동을 스스로 선택합니다.</p></div></section>
    {error&&<p className="error">{error}</p>}<section className="panel tablePanel"><table><thead><tr><th>에이전트</th><th>역할</th><th>연결 도구</th><th>반복 제한</th><th>버전</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.description}</small></td><td>{item.role==='ANALYST'?'분석관':item.role==='STAFF'?'참모':'행정병'}<small>{item.owner}</small></td><td>{item.definition.tools.length}개</td><td>최대 {item.definition.max_iterations}회</td><td><Life value={item.lifecycle}/> <small>v{item.version}</small></td><td><div className="registryActions"><button className="secondary" onClick={()=>nav('/react-agents/'+item.id+'/builder')}><Settings2/> 빌더</button><button className="primary" disabled={item.lifecycle!=='PUBLISHED'} onClick={()=>nav('/react-agents/'+item.id+'/chat')}><Play/> 실행</button>{!['react-paju-briefing','react-weekly-movement'].includes(item.id)&&<button className="danger iconDelete" onClick={()=>remove(item)}><Trash2/></button>}</div></td></tr>)}</tbody></table></section>
    {creating&&<div className="modalBackdrop" onClick={()=>setCreating(false)}><article className="createModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setCreating(false)}><X/></button><span>NEW REACT AGENT</span><h2>새 에이전트 만들기</h2><p>기본 ReAct 런타임과 네 개의 데모 도구가 연결된 초안을 만듭니다.</p><label>에이전트 이름<input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><div className="createActions"><button className="secondary" onClick={()=>setCreating(false)}>취소</button><button className="primary" onClick={create}>빌더에서 구성 <ChevronRight/></button></div></article></div>}
  </>;
}

export function ReactAgentBuilder({session}:{session:Session}){
  const {id}=useParams();const nav=useNavigate();const [agent,setAgent]=useState<ReactAgent>();const [tools,setTools]=useState<Tool[]>([]);const [models,setModels]=useState<any[]>([]);const [message,setMessage]=useState('');const [error,setError]=useState('');
  useEffect(()=>{Promise.all([api('/react-agents?role='+session.role,session),api('/react-tools',session),api('/models',session)]).then(async([agents,t,m])=>{setTools(t);setModels(m);const selected=id||agents[0]?.id;if(!selected){nav('/react-agents');return}setAgent(await api('/react-agents/'+selected,session))}).catch(e=>setError(e.message))},[id,session.role]);
  const enabled=agent?.definition.tools||[];
  const graph=useMemo(()=>{const selected=tools.filter(tool=>enabled.includes(tool.id));const nodes:any[]=[{id:'goal',type:'goal',position:{x:40,y:190},data:{}},{id:'core',type:'core',position:{x:370,y:180},data:{}}];const edges:any[]=[{id:'goal-core',source:'goal',target:'core',animated:true}];selected.forEach((tool,index)=>{const nodeId='tool-'+tool.id;nodes.push({id:nodeId,type:'resource',position:{x:720,y:35+index*115},data:{label:tool.name,kind:tool.kind}});edges.push({id:'core-'+nodeId,source:'core',target:nodeId,animated:true});edges.push({id:nodeId+'-core',source:nodeId,target:'core'})});return {nodes,edges}},[tools,enabled.join('|')]);
  if(!agent)return <div className="loading">{error||'에이전트 빌더를 불러오는 중…'}</div>;
  const updateDefinition=(patch:any)=>setAgent({...agent,definition:{...agent.definition,...patch},lifecycle:'DRAFT'});
  function toggleTool(toolId:string){updateDefinition({tools:enabled.includes(toolId)?enabled.filter((x:string)=>x!==toolId):[...enabled,toolId]})}
  async function save(){const current=agent;if(!current)return;try{await api('/react-agents/'+current.id,session,{method:'PUT',body:JSON.stringify({name:current.name,description:current.description,definition:current.definition})});setAgent({...current,lifecycle:'DRAFT'});setMessage('에이전트 초안을 저장했습니다.')}catch(e:any){setError(e.message)}}
  async function publish(){const current=agent;if(!current)return;try{await api('/react-agents/'+current.id,session,{method:'PUT',body:JSON.stringify({name:current.name,description:current.description,definition:current.definition})});const result=await api('/react-agents/'+current.id+'/publish',session,{method:'POST'});setAgent({...current,lifecycle:'PUBLISHED',version:result.version});setMessage(`에이전트 v${result.version}을 게시했습니다.`)}catch(e:any){setError(e.message)}}
  return <div className="reactBuilderPage"><div className="builderHead"><div><span>REACT AGENT BUILDER</span><h1>{agent.name}</h1><div><Life value={agent.lifecycle}/><small>v{agent.version} · 도구 {enabled.length}개 연결</small></div></div><div className="builderActions"><button className="secondary" onClick={save}><Save/> 저장</button><button className="primary" onClick={publish}><Check/> 게시</button><button className="secondary" disabled={agent.lifecycle!=='PUBLISHED'} onClick={()=>nav('/react-agents/'+agent.id+'/chat')}><Play/> 채팅 실행</button></div></div>
    {(message||error)&&<div className={error?'builderNotice error':'builderNotice'}>{error||message}</div>}
    <div className="reactBuilder"><aside className="reactPalette"><h3>외부 시스템과 기능</h3><p>에이전트가 판단에 따라 사용할 수 있는 도구를 연결합니다.</p>{tools.map(tool=><button key={tool.id} className={enabled.includes(tool.id)?'connected':''} onClick={()=>toggleTool(tool.id)}><span>{tool.kind==='database'?<Database/>:tool.kind==='search'?<Search/>:<Network/>}</span><div><b>{tool.name}</b><small>{tool.description}</small></div><strong>{enabled.includes(tool.id)?'연결됨':'연결'}</strong></button>)}</aside>
      <main className="reactCanvas"><ReactFlow nodes={graph.nodes} edges={graph.edges} nodeTypes={nodeTypes} fitView nodesDraggable={false} nodesConnectable={false} elementsSelectable={false}><Background color="#cbd5e1" gap={24}/><Controls/><MiniMap/></ReactFlow><div className="canvasLabel"><span className="online"/> 연결된 도구를 ReAct 런타임이 상황에 따라 선택합니다.</div></main>
      <aside className="reactSettings"><h3>에이전트 설정</h3><label>이름<input value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value,lifecycle:'DRAFT'})}/></label><label>설명<textarea value={agent.description} onChange={e=>setAgent({...agent,description:e.target.value,lifecycle:'DRAFT'})}/></label><label>모델<select value={agent.definition.model.model_id} onChange={e=>updateDefinition({model:{...agent.definition.model,model_id:e.target.value}})}>{models.map(model=><option key={model.id}>{model.id}</option>)}</select></label><label>최대 반복 횟수<input type="number" min="5" max="8" value={agent.definition.max_iterations} onChange={e=>updateDefinition({max_iterations:+e.target.value})}/><small>도구 선택과 관찰을 포함해 5~8회로 제한합니다.</small></label><label>시스템 프롬프트<textarea className="prompt" value={agent.definition.system_prompt} onChange={e=>updateDefinition({system_prompt:e.target.value})}/></label><div className="info">API 키와 외부 시스템 자격 증명은 백엔드 환경에서만 관리합니다.</div></aside>
    </div></div>;
}

export function ReactAgentChat({session}:{session:Session}){
  const {id}=useParams();const initialized=useRef('');const [agent,setAgent]=useState<ReactAgent>();const [prompt,setPrompt]=useState(session.role==='ADMIN'?'이번 주차 외출/외박 현황 보고 작성해줘':'파주시 최근 이상 징후를 조사하고 지휘관 브리핑을 작성해줘');const [sessions,setSessions]=useState<ChatSession[]>([]);const [selectedSession,setSelectedSession]=useState('');const [messages,setMessages]=useState<ChatTurn[]>([]);const [submittedPrompt,setSubmittedPrompt]=useState('');const [events,setEvents]=useState<any[]>([]);const [status,setStatus]=useState('READY');const [draft,setDraft]=useState('');const [error,setError]=useState('');
  async function openSession(sessionId:string){if(!id)return;const detail=await api('/react-agents/'+id+'/sessions/'+sessionId,session);setSelectedSession(sessionId);setMessages(detail.messages);setEvents([]);setSubmittedPrompt('');setDraft('');setStatus('READY')}
  async function newSession(){if(!id)return;const created=await api('/react-agents/'+id+'/sessions',session,{method:'POST',body:JSON.stringify({title:'새 대화'})});setSessions(current=>[created,...current]);setSelectedSession(created.id);setMessages([]);setEvents([]);setSubmittedPrompt('');setDraft('');setStatus('READY')}
  async function removeSession(sessionId:string){if(!id||status==='RUNNING'||!confirm('이 대화와 실행 기록을 삭제하시겠습니까?'))return;await api('/react-agents/'+id+'/sessions/'+sessionId,session,{method:'DELETE'});const remaining=sessions.filter(item=>item.id!==sessionId);if(remaining.length){setSessions(remaining);await openSession(remaining[0].id)}else{const created=await api('/react-agents/'+id+'/sessions',session,{method:'POST',body:JSON.stringify({title:'새 대화'})});setSessions([created]);setSelectedSession(created.id);setMessages([]);setEvents([]);setSubmittedPrompt('');setDraft('');setStatus('READY')}}
  useEffect(()=>{if(!id)return;const key=id+':'+session.role;if(initialized.current===key)return;initialized.current=key;Promise.all([api('/react-agents/'+id,session),api('/react-agents/'+id+'/sessions',session)]).then(async([loadedAgent,loadedSessions])=>{setAgent(loadedAgent);setSessions(loadedSessions);if(loadedSessions.length)await openSession(loadedSessions[0].id);else await newSession()}).catch(e=>setError(e.message))},[id,session.role]);
  async function run(){if(!id||!selectedSession||!prompt.trim())return;const request=prompt.trim();setSubmittedPrompt(request);setEvents([]);setDraft('');setError('');setStatus('RUNNING');try{const response=await fetch(API+'/react-agents/'+id+'/runs/stream',{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Role':session.role},body:JSON.stringify({prompt:request,session_id:selectedSession})});if(!response.ok)throw new Error((await response.json()).detail||response.statusText);const reader=response.body!.getReader();const decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='answer_chunk')setDraft(current=>current+event.content);else{setEvents(current=>[...current,event]);if(event.type==='completed'){const answer=event.payload?.answer||'';setMessages(current=>[...current,{id:event.run_id,prompt:request,answer,status:'COMPLETED',created_at:event.created_at}]);setSessions(current=>current.map(item=>item.id===selectedSession?{...item,title:item.title==='새 대화'?request.slice(0,32):item.title,turn_count:item.turn_count+1,updated_at:event.created_at}:item));setSubmittedPrompt('');setDraft('');setPrompt('');setStatus('COMPLETED')}if(event.type==='error'){setStatus('FAILED');setError(event.content)}}}if(done)break}}catch(e:any){setStatus('FAILED');setError(e.message)}}
  return <><Header eyebrow="REACT AGENT CHAT" title={agent?.name||'에이전트 실행'}><span className={'agentRunStatus '+status.toLowerCase()}>{status==='READY'?'실행 준비':status==='RUNNING'?'조사 중':status==='COMPLETED'?'완료':'실패'}</span></Header>
    <div className="agentChatLayout"><aside className="chatSessions panel"><button className="secondary newChat" onClick={newSession} disabled={status==='RUNNING'}><MessageSquarePlus/> 새 대화</button><small>최근 3턴을 컨텍스트로 사용</small><div>{sessions.map(item=><article key={item.id} className={selectedSession===item.id?'active':''}><button disabled={status==='RUNNING'} onClick={()=>openSession(item.id)}><b>{item.title}</b><span>{item.turn_count}턴</span></button><button className="removeChat" title="대화 삭제" disabled={status==='RUNNING'} onClick={()=>removeSession(item.id)}><Trash2/></button></article>)}</div></aside><section className="agentChat panel"><div className="chatContext"><Bot/><div><b>{agent?.name}</b><small>ReAct · 도구 {agent?.definition.tools.length||0}개 · 최대 {agent?.definition.max_iterations||0}회 · 컨텍스트 3턴</small></div></div><div className="chatMessages">{messages.map(message=><React.Fragment key={message.id}><article className="chatBubble user"><small>사용자</small><p>{message.prompt}</p></article><article className="chatBubble assistant"><small>에이전트 분석 결과</small><p>{message.answer}</p></article></React.Fragment>)}{submittedPrompt&&<article className="chatBubble user"><small>사용자</small><p>{submittedPrompt}</p></article>}{!messages.length&&!submittedPrompt&&status==='READY'&&<div className="chatEmpty"><Bot/><b>조사 목표를 입력하세요.</b><p>에이전트가 연결된 데이터와 기능 중 필요한 도구를 직접 선택합니다.</p></div>}{draft&&<article className="chatBubble assistant"><small>에이전트 분석 결과</small><p>{draft}</p></article>}{error&&<p className="error">{error}</p>}</div><div className="chatComposer"><textarea value={prompt} disabled={status==='RUNNING'} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run()}}}/><button className="primary" onClick={run} disabled={status==='RUNNING'||!selectedSession}><Send/> 실행</button></div></section>
      <aside className="agentTrace panel"><div className="panelTitle"><h2>판단 및 도구 실행 과정</h2><span>{events.length}단계</span></div><div className="agentTimeline">{events.map((event,index)=><article key={event.id||index} className={'agentEvent '+event.type}><span>{event.type==='tool_result'?<Check/>:event.type==='reasoning'?<Bot/>:<Play/>}</span><div><small>{event.type==='reasoning'?'판단 요약':event.type==='tool_result'?'도구 관찰':'실행 상태'}</small><b>{event.title}</b><p>{event.content}</p>{event.tool_name&&<em>{event.tool_name}</em>}</div></article>)}</div><div className="traceNotice">모델의 비공개 사고 과정 대신 사용자에게 설명 가능한 판단 요약과 도구 실행 결과를 표시합니다.</div></aside>
    </div></>;
}
